name: Built .NET client

on:
  push:
    branches: [ "feature/ci-dotnet" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Test
        run: dotnet test
        working-directory: clients/Dotnet
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Extract version from tag
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="0.0.0"
          fi
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: clients/Dotnet
          
      # extract version from tag
      - name: Pack
        run: dotnet pack -c Release --property:Version=${{env.VERSION}}
        working-directory: clients/Dotnet
        
      # Save as an artifact
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          path: 'clients/Dotnet/MarkItDownApiClient/bin/Release/MarkItDownApi.Client.*.nupkg'
          name: 'nuget-package'
          
  nuget-publish:
    runs-on: ubuntu-latest
    needs: build-and-push
#    if: github.event_name == 'push' && github.ref == 'refs/tags/v*.*.*'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
          
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: package
          
      - name: List files
        run: ls package
        
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/tags/v*.*.*'
        run: dotnet nuget push package/MarkItDownApi.Client.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
